### ISSUE TITLE
运行 conda env create -f llm.yml报错：

### ISSUE THREAD

**Issue by puallee** [openmedlab/PULSE#14]
运行 conda env create -f llm.yml报错：

An unexpected error has occurred. Conda has prepared the above report.

Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
    return func(*args, **kwargs)
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/conda_env/cli/main.py", line 80, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/conda_env/cli/main_create.py", line 118, in execute
    result[installer_type] = installer.install(prefix, pkg_specs, args, env)
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/conda_env/installers/conda.py", line 31, in install
    unlink_link_transaction = solver.solve_for_transaction(
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 114, in solve_for_transaction
    unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 157, in solve_for_diff
    final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 262, in solve_final_state
    ssc = self._collect_all_metadata(ssc)
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 397, in _collect_all_metadata
    _supplement_index_with_system(virtual_pkg_index)
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/conda/core/index.py", line 163, in _supplement_index_with_system
    dist_name, dist_version = context.os_distribution_name_version
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/conda/_vendor/auxlib/decorators.py", line 268, in new_fget
    cache[inner_attname] = func(self)
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/conda/base/context.py", line 786, in os_distribution_name_version
    from .._vendor.distro import id, version
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/conda/_vendor/distro.py", line 1084, in <module>
    _distro = LinuxDistribution()
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/conda/_vendor/distro.py", line 599, in __init__
    self._lsb_release_info = self._get_lsb_release_info() \
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/conda/_vendor/distro.py", line 943, in _get_lsb_release_info
    raise subprocess.CalledProcessError(code, cmd, stdout, stderr)
subprocess.CalledProcessError: Command 'lsb_release -a' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/bin/conda-env", line 7, in <module>
    sys.exit(main())
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/conda_env/cli/main.py", line 91, in main
    return conda_exception_handler(do_call, args, parser)
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1371, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1082, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1126, in handle_exception
    return self.handle_unexpected_exception(exc_val, exc_tb)
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1141, in handle_unexpected_exception
    self._execute_upload(error_report)
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1303, in _execute_upload
    'User-Agent': self.user_agent,
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1101, in user_agent
    return context.user_agent
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/conda/_vendor/auxlib/decorators.py", line 268, in new_fget
    cache[inner_attname] = func(self)
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/conda/base/context.py", line 744, in user_agent
    builder.append("%s/%s" % self.os_distribution_name_version)
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/conda/_vendor/auxlib/decorators.py", line 268, in new_fget
    cache[inner_attname] = func(self)
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/conda/base/context.py", line 786, in os_distribution_name_version
    from .._vendor.distro import id, version
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/conda/_vendor/distro.py", line 1084, in <module>
    _distro = LinuxDistribution()
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/conda/_vendor/distro.py", line 599, in __init__
    self._lsb_release_info = self._get_lsb_release_info() \
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/conda/_vendor/distro.py", line 943, in _get_lsb_release_info
    raise subprocess.CalledProcessError(code, cmd, stdout, stderr)
subprocess.CalledProcessError: Command 'lsb_release -a' returned non-zero exit status 1.

**Comment by genggui001** [comment]
求运行一下
lsb_release -a
这个命令，然后贴一波结果
